### PR TITLE
Allow constructing a Controller without specifying generic parameters

### LINKED ISSUE #61: Default values for const generic parameters MAX_DIRS, MAX_FILES, don't work as expected.
Commit https://github.com/rust-embedded-community/embedded-sdmmc-rs/commit/566f2023653dace195a43b05a6429f47e6be8a50 added two const generic parameters `MAX_DIRS` and `MAX_FILES` to `Controller`.

Those parameters have default values equal to the values used before, and the new docs say: "By default the `Controller` will initialize with a maximum number of `4` open directories and files. This can be customized by specifying the `MAX_DIR` and `MAX_FILES` generic consts of the `Controller`"

However, the default values don't work as expected. The following code causes a compile failure:
```
let mut cont = Controller::new(block, DummyTimesource::default());
```
```
error[E0282]: type annotations needed for `embedded_sdmmc::Controller<BlockSpi<'_, rp_pico::rp2040_hal::Spi<rp_pico::rp2040_hal::spi::Enabled, SPI0, 8>, rp_pico::rp2040_hal::gpio::Pin<Gpio5, rp_pico::rp2040_hal::gpio::Output<rp_pico::rp2040_hal::gpio::PushPull>>>, DummyTimesource, MAX_DIRS, MAX_FILES>`
   --> boards/rp-pico/examples/pico_spi_sd_card.rs:276:9
    |
276 |     let mut cont = Controller::new(block, DummyTimesource::default());
    |         ^^^^^^^^
    |
help: consider giving `cont` an explicit type, where the the value of const parameter `MAX_DIRS` is specified
    |
276 |     let mut cont: embedded_sdmmc::Controller<BlockSpi<'_, rp_pico::rp2040_hal::Spi<rp_pico::rp2040_hal::spi::Enabled, SPI0, 8>, rp_pico::rp2040_hal::gpio::Pin<Gpio5, rp_pico::rp2040_hal::gpio::Output<rp_pico::rp2040_hal::gpio::PushPull>>>, DummyTimesource, MAX_DIRS, MAX_FILES> = Controller::new(block, DummyTimesource::default());
    |                 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0282`.
```
(This was noticed in `rp-hal`, see [this ticket](https://github.com/rp-rs/rp-hal/pull/426) for context.)

There is a blog post which nicely explains why this happens: https://gankra.github.io/blah/defaults-affect-inference/#default-type-parameters

### PR DESCRIPTION
**Pull request by jannic**
Fixes #61

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
The function name sounds fine to me.
Some alternatives: `new_custom_limits`, `new_with_limits`

**Comment by jannic** [comment]
I think `new_with_limits` is indeed better than `new_custom_max`. The word `with` makes the meaning clearer. While `new_with_custom_max` or `new_with_custom_limits` would be possible as well, they are just too long. If there are no other proposals, I'll change the name to `new_with_limits`.

**Comment by jannic** [comment]
@thejpster suggested `with_capacity` in https://github.com/rust-embedded-community/embedded-sdmmc-rs/issues/61#issuecomment-1384652373
Also a good suggestion. Or should that be reserved to container types, to avoid confusion?

**Comment by eldruin** [comment]
@jannic have you decided on keeping `new_with_limits`?
Could you move both unreleased changelog entries to the 0.4.0 version section?

**Comment by jannic** [comment]
> @jannic have you decided on keeping `new_with_limits`?

I don't think I should make that decision. I don't even use this crate, so I may misunderstand how it is used in practice.
From my side, it's fine as it is. Feel free to merge it if you like it.

> Could you move both unreleased changelog entries to the 0.4.0 version section?

Sure. But I feel like the unreleased section is not used correctly at the moment. The whole 0.4.0 section shouldn't exist yet and should only be created when doing the release. The way it's done now, neither the "Unreleased" link, https://github.com/rust-embedded-community/embedded-sdmmc-rs/compare/v0.4.0...develop, nor the "Version 0.4.0" link, https://github.com/rust-embedded-community/embedded-sdmmc-rs/releases/tag/v0.4.0, point to useful contents.

**Review by eldruin — APPROVED** [review]
Thanks! Let's get this merged then.
There was a release hold off after merging the 0.4.0 version bump, which lead to this weird situation in the changelog.
I will release version 0.4.0 shortly.

**Pull request merged**
