### PR TITLE
Add LFN support when iterating directories

### PR DESCRIPTION
**Pull request by jonathanpallant**
You can now optionally see the long file names when doing directory listings. To do so you must pass an `LfnBuffer` of your chosen size to the new `iterate_dir_lfn` methods.

### CODE REVIEW

**Comment by thejpster** [comment]
ugh, dealing with the fact that one unicode character might become two UTF-16 code units, and those two code units could be split across two directory entries, was a nightmare. But I think this works.

**Review by eldruin — COMMENTED** [review]
Looks good to me, thanks!
Could you add an entry to the changelog about this?

**Comment by thejpster** [comment]
> Looks good to me, thanks! Could you add an entry to the changelog about this?

Done

**Review by eldruin — APPROVED** [review]
Thank you for your work!

**Pull request merged**
