### PR TITLE
optionally use defmt + add defmt::Format to required structs

### PR DESCRIPTION
**Pull request by gauteh**
Would this be of interest?

### CODE REVIEW

**Review by jonathanpallant — APPROVED** [review]

**Review by eldruin — COMMENTED** [review]
Looks good to me. Could you add an entry to the changelog?

**Comment by gauteh** [comment]
Changelog entry added.

**Comment by eldruin** [comment]
There are some problems building this. Could you have a look?
Could you also adapt the CI to test this feature as well and also document this feature both in the README and in the `lib.rs`?

**Comment by gauteh** [comment]
Had to make some minor changes, please re-run CI.

**Comment by eldruin** [comment]
There is an error in the script preventing execution:
```
Error : .github#L1
every step must define a `uses` or `run` key
```

**Review by eldruin — COMMENTED** [review]
Looks good! One last thing before the merge, though: Could you also improve the CI to run without any features i.e. just `--no-default-flags`?
One easy way to do this is to change the `features` values to `['', '--features log', '--features defmt-log']` and adapt the rest accordingly

**Comment by gauteh** [comment]
> Looks good! One last thing before the merge, though: Could you also improve the CI to run without any features i.e. just `--no-default-flags`? One easy way to do this is to change the `features` values to `['', '--features log', '--features defmt-log']` and adapt the rest accordingly

That won't work as it is now, you have to select a logger.

**Review by eldruin — APPROVED** [review]
Interesting. Ok, then let's merge this as-is.
Thank you for your work!

**Pull request merged**
