### PR TITLE
Release v0.5.0

### PR DESCRIPTION
**Pull request by thejpster**
## Changes

- __Breaking Change__: Renamed `Controller` to `VolumeManager`, to better describe what it does.
- __Breaking Change__: Renamed `SdMmcSpi` to `SdCard`
- __Breaking Change__: `AcquireOpts` now has `use_crc` (which makes it ask for CRCs to be enabled) instead of `require_crc` (which simply allowed the enable-CRC command to fail)
- __Breaking Change__: `SdCard::new` now requires an object that implements the embedded-hal `DelayUs` trait
- __Breaking Change__: Renamed `card_size_bytes` to `num_bytes`, to match `num_blocks`
- More robust card intialisation procedure, with added retries
- Supports building with neither `defmt` nor `log` logging

## Added

- Added `mark_card_as_init` method, if you know the card is initialised and want to skip the initialisation step

## Removed

- __Breaking Change__: Removed `BlockSpi` type - card initialisation now handled as an internal state variable

### CODE REVIEW

**Comment by thejpster** [comment]
Hey @rust-embedded-community/all, can I get a look over this new release? Thanks!

**Comment by elpiel** [comment]
@thejpster looks good, I've migrated my code to this new version and will test tomorrow.

PS: Maybe the team is not public but I don't see if you tagged the `rust-embedded-community/all` team

**Comment by thejpster** [comment]
Pinging @rust-embedded-community/all

**Comment by thejpster** [comment]
Ahh, https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#inline-and-no_inline is a good idea, yes. I'll open a ticket for that.

**Review by eldruin — APPROVED** [review]
Impressive amount of work, thank you!

**Comment by jonathanpallant** [comment]
Did you merge the missing field fix before merging the release?

Also: someone needs to tag the main branch and do a cargo publish.

**Comment by eldruin** [comment]
> @eldruin did you merge the unused field fix before merging the release?

yes, I did.

**Comment by thejpster** [comment]
Ah but this release branch targets main and not develop. So changes that appear after the branch is cut need merging into the release as well otherwise they are missed. It allows you to have experimental work going on but still have a relatively stable release branch for pre-release testing.

**Comment by eldruin** [comment]
I see. I did not notice the branch difference, sorry about that.

**Pull request merged**
