### PR TITLE
Set rust-version to 1.76 & add matrix for building and testing for MSRV

### LINKED ISSUE #166: Consider an appropriate MSRV
Since we are moving forward with implementations that will bring async support I think it's good time to talk about MSRV.

`async_fn_in_trait` has been stabalised in `1.75.0` and I think we can start from there.
I can:
- [ ] tweak the CI to include MSRV build
as well as
- [ ] change the Cargo.toml to include `rust-version = "1.75"`

### PR DESCRIPTION
**Pull request by elpiel**
closes #166

### CODE REVIEW

**Comment by thejpster** [comment]
> exclusive range pattern syntax is experimental

oops. Should be easily fixable.

**Comment by elpiel** [comment]
Yeah, they are easy to fix.
Will get to that.

**Comment by elpiel** [comment]
I fixed the pattern matching but this `trim_ascii_end` is giving me a headache.
Any ideas how to replace it?

**Comment by thejpster** [comment]
You could just copy/paste the source code from the newer library:

```rust
impl VolumeName {
    pub fn name(&self) -> &[u8] {
        let mut bytes = &self.0[..];
        while let [rest @ .., last] = bytes {
            if last.is_ascii_whitespace() {
                bytes = rest;
            } else {
                break;
            }
        }
        bytes
    }
}
```

**Comment by elpiel** [comment]
Yep, that should do the trick.
I think I initially just used `&self.content` which didn't work.

Checks are passing now :tada:

**Comment by thejpster** [comment]
Yeah because Volume Names are padded with space characters.

**Comment by thejpster** [comment]
The build tasks have been renamed so CI is sad because the job it wants to see didn't run.

The configuration for which jobs are mandatory should be in git, but it's not. It's hidden in GitHub's proprietary back-end.

**Pull request merged**
