### PR TITLE
Skip wait init sequence

### PR DESCRIPTION
**Pull request by elpiel**
Continuing the fix from PR #73

### CODE REVIEW

**Comment by thejpster** [comment]
I'll try and get this running on hardware and give it a spin.

**Comment by elpiel** [comment]
Thank you @thejpster !
Using the crate for raw access only hasn't given me problems ever since I switched to this fix.

Let me know if you find anything.

**Comment by thejpster** [comment]
Taking baby steps. My PCB can now detect the card has been inserted, so I need to fix #77 and then I can start testing this out.

**Comment by UserJHansen** [comment]
This works for me

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
Ok let's goooooo

**Comment by elpiel** [comment]
Whoooooohoooo :raised_hands:

**Pull request merged**
