### PR TITLE
fix: on multi-block writes send ACMD23 and wait not busy

### PR DESCRIPTION
**Pull request by elpiel**
- Wait not busy fixes multiblock writes at least for the SD card I was using (SanDisk extreme 32 GB) otherwise I was getting a Timeout
- Sending ACMD23 can considerably improve writing speeds for some cards which pre-erase the blocks.

### CODE REVIEW

**Review by jonathanpallant — APPROVED** [review]
LGTM, thanks!

**Comment by elpiel** [comment]
Thanks for acting quick 😋

**Comment by jonathanpallant** [comment]
If you have a moment, you might like to take a look at #95

**Comment by elpiel** [comment]
Yes, will do! Sadly I do not use the Fat32 implementation any more but I will be happy to take a look at the PR and provide feedback.

**Pull request merged**
